### ISSUE TITLE
main.py does not exist

### ISSUE THREAD

**Issue by fractalliter** [M91skr/Make_a_Blog#2]
In [README.md](https://github.com/M91skr/Make_a_Blog/blob/master/README.md) file under **How to run** section, [the command for executing the application with python](https://github.com/M91skr/Make_a_Blog/blob/8cdc823757301dac04ba834bbebdadcc1aeead1e/README.md?plain=1#L18) throws an error.

You must change the `main.py` to `server.py` to fix the problem.

**Comment by M91skr** [comment]
Thanks for reporting the issue. :+1:
